# This service is responsible for the build stage.
# For this project, that involves downloading dependencies.

include:
  - ./cloner.yml

services:
  builder:
    image: docker.io/composer:2.9
    command: /bin/sh -c "composer install && composer dump-autoload"
    networks:
      - oravox_player_network
    depends_on:
      cloner:
        condition: service_completed_successfully
    working_dir: /var/www/html
    volumes:
      - web:/var/www/html
      - composer_cache:/tmp
  migration:
    image: docker.io/bitnami/php-fpm:latest
    depends_on:
      mariadb:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    entrypoint: ["/init.sh"]
    networks:
      - oravox_player_network
    volumes:
      - web:/var/www/html
      - ./.env-app:/var/www/html/.env:ro
      - ./docker/builder/migration/migration.sh:/init.sh:ro
    env_file: .env
    working_dir: $WWW_DIR

volumes:
  composer_cache:
